services:
  postgres:
    image: postgres
    env_file: .env
    ports:
      - "${PORTOUT}:${PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "${PORTO}:${PORTD}"
    depends_on:
      - postgres

volumes:
  postgres_data: {}


  

  
